# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
            - api
            - two_factor
            - test_run_api
            - user_api
            - env_variable_api
            - cron_job_api
            - test_discovery
